/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as HomeImport } from './routes/home'
import { Route as IndexImport } from './routes/index'
import { Route as HomeIndexImport } from './routes/home/index'
import { Route as HomeSettingsImport } from './routes/home/settings'
import { Route as HomeReportsImport } from './routes/home/reports'
import { Route as HomeGoalsImport } from './routes/home/goals'
import { Route as HomeCalendarImport } from './routes/home/calendar'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)

const HomeSettingsRoute = HomeSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HomeRoute,
} as any)

const HomeReportsRoute = HomeReportsImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => HomeRoute,
} as any)

const HomeGoalsRoute = HomeGoalsImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => HomeRoute,
} as any)

const HomeCalendarRoute = HomeCalendarImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => HomeRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/home/calendar': {
      id: '/home/calendar'
      path: '/calendar'
      fullPath: '/home/calendar'
      preLoaderRoute: typeof HomeCalendarImport
      parentRoute: typeof HomeImport
    }
    '/home/goals': {
      id: '/home/goals'
      path: '/goals'
      fullPath: '/home/goals'
      preLoaderRoute: typeof HomeGoalsImport
      parentRoute: typeof HomeImport
    }
    '/home/reports': {
      id: '/home/reports'
      path: '/reports'
      fullPath: '/home/reports'
      preLoaderRoute: typeof HomeReportsImport
      parentRoute: typeof HomeImport
    }
    '/home/settings': {
      id: '/home/settings'
      path: '/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof HomeSettingsImport
      parentRoute: typeof HomeImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof HomeImport
    }
  }
}

// Create and export the route tree

interface HomeRouteChildren {
  HomeCalendarRoute: typeof HomeCalendarRoute
  HomeGoalsRoute: typeof HomeGoalsRoute
  HomeReportsRoute: typeof HomeReportsRoute
  HomeSettingsRoute: typeof HomeSettingsRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeCalendarRoute: HomeCalendarRoute,
  HomeGoalsRoute: HomeGoalsRoute,
  HomeReportsRoute: HomeReportsRoute,
  HomeSettingsRoute: HomeSettingsRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/signup': typeof SignupRoute
  '/home/calendar': typeof HomeCalendarRoute
  '/home/goals': typeof HomeGoalsRoute
  '/home/reports': typeof HomeReportsRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home/': typeof HomeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/home/calendar': typeof HomeCalendarRoute
  '/home/goals': typeof HomeGoalsRoute
  '/home/reports': typeof HomeReportsRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home': typeof HomeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/signup': typeof SignupRoute
  '/home/calendar': typeof HomeCalendarRoute
  '/home/goals': typeof HomeGoalsRoute
  '/home/reports': typeof HomeReportsRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home/': typeof HomeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/signup'
    | '/home/calendar'
    | '/home/goals'
    | '/home/reports'
    | '/home/settings'
    | '/home/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/home/calendar'
    | '/home/goals'
    | '/home/reports'
    | '/home/settings'
    | '/home'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/signup'
    | '/home/calendar'
    | '/home/goals'
    | '/home/reports'
    | '/home/settings'
    | '/home/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRouteWithChildren
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRouteWithChildren,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/home",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/home": {
      "filePath": "home.tsx",
      "children": [
        "/home/calendar",
        "/home/goals",
        "/home/reports",
        "/home/settings",
        "/home/"
      ]
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/home/calendar": {
      "filePath": "home/calendar.tsx",
      "parent": "/home"
    },
    "/home/goals": {
      "filePath": "home/goals.tsx",
      "parent": "/home"
    },
    "/home/reports": {
      "filePath": "home/reports.tsx",
      "parent": "/home"
    },
    "/home/settings": {
      "filePath": "home/settings.tsx",
      "parent": "/home"
    },
    "/home/": {
      "filePath": "home/index.tsx",
      "parent": "/home"
    }
  }
}
ROUTE_MANIFEST_END */
